// Code generated by tygo. DO NOT EDIT.

//////////
// source: pisterajat.go
/*
Package pisterajat converts admission cutoff CSV data into a hierarchical
JSON-friendly representation.
*/

/**
 * School contains every programme offered by one school.
 */
export interface School {
  name: string;
  programmes: Programme[];
}
/**
 * Programme contains the cutoff scores grouped by selection method.
 */
export interface Programme {
  name: string;
  selectionMethods: SelectionMethod[];
}
/**
 * SelectionMethod contains the cutoff scores for one selection method.
 */
export interface SelectionMethod {
  name: string;
  cutoffs: Cutoff[];
}
/**
 * Cutoff is one admission cutoff score and its qualifier.
 */
export interface Cutoff {
  detail: string;
  score: number /* float64 */;
}
