// Code generated by tygo. DO NOT EDIT.

//////////
// source: pisterajat.go
/*
Package pisterajat converts admission cutoff CSV data into a hierarchical
JSON-friendly representation.
*/

/**
 * School contains every programme offered by one school.
 */
export interface School {
  name: string;
  sector: string;
  programmes: Programme[];
}
/**
 * Programme contains the cutoff scores for one programme.
 */
export interface Programme {
  name: string;
  koulutusala: string;
  cutoffs: Cutoff[];
}
/**
 * Cutoff is one selection method and its admission cutoff score.
 */
export interface Cutoff {
  selectionMethod: string;
  score: number /* float64 */;
  startYear: number /* int */;
  startSeason: string;
}
