// Code generated by tygo. DO NOT EDIT.

//////////
// source: opintopolku.go

export interface OpintopolkuData {
  total: number /* int */;
  hits: School[];
}
export interface School {
  koulutukset: Koulutus[];
  toteutukset: Toteutus[];
}
export interface Toteutus {
  toteutusOid: string;
  toteutusNimi: LanguageStrings;
  oppilaitosNimi: LanguageStrings;
}
export interface Koulutus {
  nimi: LanguageStrings;
}
export interface LanguageStrings {
  fi?: string;
  sv?: string;
  en?: string;
}

//////////
// source: vipunen.go

export interface VipunenData {
  kooditHakukohde: string;
  hakukohde: string;
  korkeakoulu: string;
  aloituspaikatLkm?: number /* int */;
  kaikkiHakijatLkm?: number /* int */;
  ensisijaisetHakijatLkm?: number /* int */;
  koulutuksenKieli: string;
  sektori: string;
  koulutusalaTaso1: string;
}
