// Code generated by tygo. DO NOT EDIT.

//////////
// source: config.go

export interface Config {
  vipunen: VipunenConfig;
  opintopolku: OpintopolkuConfig;
}
export interface VipunenConfig {
  aineistoUrl: string;
  tilastoVuosi: number /* int */;
  hakutapa: string;
}
export interface OpintopolkuConfig {
  yhteishakuOid: string;
  alkamisajankohdat: string[];
}

//////////
// source: meta.go

export interface Meta {
  generatedAt: string /* RFC3339 */;
  statisticsRounds: string[];
  currentStatisticsRound: string;
  statisticsUpdatedAt?: string /* RFC3339 */;
  programmesUpdatedAt?: string /* RFC3339 */;
  programmesYhteishakuOid?: string;
}

//////////
// source: opintopolku.go

export interface OpintopolkuData {
  total: number /* int */;
  hits: School[];
}
export interface School {
  koulutukset: Koulutus[];
  toteutukset: Toteutus[];
  koulutustyyppi: string;
}
export interface Toteutus {
  toteutusOid: string;
  toteutusNimi: LanguageStrings;
  oppilaitosNimi: LanguageStrings;
  kunnat: Kunta[];
}
export interface Kunta {
  nimi: LanguageStrings;
}
export interface Koulutus {
  nimi: LanguageStrings;
}
export interface LanguageStrings {
  fi?: string;
  sv?: string;
  en?: string;
}
/**
 * SchoolsResponse is the optimized schools.json format:
 * a flat array of koulutus entries, each with its name (fi + en) and toteutukset.
 */
export type SchoolsResponse = KoulutusEntry[];
export interface KoulutusEntry {
  nimi: LanguageStrings;
  koulutustyyppi: string;
  toteutukset: ToteutusEntry[];
}
export interface ToteutusEntry {
  toteutusOid: string;
  toteutusNimi: LanguageStrings;
  oppilaitosNimi: LanguageStrings;
  kunnat: string[];
}

//////////
// source: vipunen.go

/**
 * StatisticsResponse is the statistics.json format.
 */
export type StatisticsResponse = StatisticsEntry[];
/**
 * StatisticsEntry is the merged statistics JSON shape.
 */
export interface StatisticsEntry {
  kooditHakukohde: string;
  hakukohde: string;
  korkeakoulu?: string;
  kuntaHakukohde?: string;
  maakuntaHakukohde?: string;
  koulutuksenKieli?: string;
  sektori?: string;
  koulutusasteTaso1?: string;
  koulutusalaTaso1?: string;
  okmOhjauksenAla?: string;
  aloituspaikatLkm: number /* int */;
  kaikkiHakijatLkm: number /* int */;
  ensisijaisetHakijatLkm: number /* int */;
}
