name: Website Deployment
on:
  push:
    branches:
      - main
    paths:
      - frontend/**
      - .github/workflows/website-deploy.yml
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6
        with:
          version: 10
      - run: pnpm install
      - run: pnpm run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.8.0
        with:
          branch: gh-pages
          folder: frontend/dist/client
          clean: true
          single-commit: true
permissions:
  contents: write
